# Generated by Django 4.1.4 on 2023-01-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grewon', '0002_user_admin_user_is_active_user_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='user',
        ),
        migrations.AddField(
            model_name='events',
            name='user',
            field=models.ManyToManyField(to='grewon.user'),
        ),
    ]
