# Generated by Django 4.1.4 on 2023-01-18 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grewon', '0003_remove_events_user_events_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grewon.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grewon.user')),
            ],
        ),
    ]
