# Generated by Django 4.1.4 on 2023-01-18 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grewon', '0004_eventuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='user',
        ),
    ]
